---

- name: "Install dependeies packages for Funkwhale"
  package:
    name:
      - python-psycopg2
      - libldap2-dev
      - libsasl2-dev
      - build-essential
      - ffmpeg
      - libjpeg-dev
      - libmagic-dev
      - libpq-dev
      - python3-dev
      - python3-venv
      - python3-psycopg2
      - gpg
    state: present

- name: "Install pgdg package signing key (Debian/pgdg)"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8
  register: __postgresql_apt_key_result
  until: __postgresql_apt_key_result is succeeded
  retries: 5
  delay: 5

- name: "Install pgdg repository (Debian/pgdg)"
  apt_repository:
    repo: "deb {{ FUNKWHALE_DB_REPO }}/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: true

- name: "Prepare of ENV.INFRA for Funkwhale"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "postgresql-{{ FUNKWHALE_DB_VER }}"
    - "postgresql-client-{{ FUNKWHALE_DB_VER }}"
    - redis-server
    - nginx

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/postgresql/{{ FUNKWHALE_DB_VER }}/main/PG_VERSION"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start and enable postgresql.service"
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: "Revoke access from local user postgres on database all"
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ FUNKWHALE_DB_VER }}/main/pg_hba.conf"
    contype: local
    users: postgres
    databases: all
    method: peer
    state: absent
  tags: molecule-idempotence-notest

- name: "Revoke access from local user all on database all"
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ FUNKWHALE_DB_VER }}/main/pg_hba.conf"
    contype: host
    users: all
    databases: all
    address: "{{ item }}"
    method: md5
    state: absent
  loop:
    - "127.0.0.1/32"
    - "::1/128"
  tags: molecule-idempotence-notest

- name: "Create access from local user postgres on database all"
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ FUNKWHALE_DB_VER }}/main/pg_hba.conf"
    contype: local
    users: postgres
    databases: all
    method: trust
    create: true
  tags: molecule-idempotence-notest

- name: "Revoke access from local user funkwhale on database all"
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ FUNKWHALE_DB_VER }}/main/pg_hba.conf"
    contype: host
    users: all
    source: "{{ item }}"
    databases: all
    method: trust
    create: true
  loop:
    - "127.0.0.1/32"
    - "::1/128"
  tags: molecule-idempotence-notest

- name: "Restart SystemD unit postgresql{{ FUNKWHALE_DB_VER }}"
  ansible.builtin.systemd:
    name: "postgresql@{{ FUNKWHALE_DB_VER }}-main"
    state: restarted
    enabled: true

- name: "Create database for app.funkwhale"
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    state: present
    encoding: UTF-8
    template: template0
  loop:
    - "{{ funkwhale_db_user }}"
    - "{{ funkwhale_db }}"
  tags: molecule-idempotence-notest

- name: "Create {{ funkwhale_db_user }} user"
  community.postgresql.postgresql_user:
    state: present
    name: "{{ funkwhale_db_user }}"
    password: ""
    role_attr_flags: SUPERUSER

- name: "Grant db {{ funkwhale_db_user }} access to {{ funkwhale_db }}"
  community.postgresql.postgresql_privs:
    type: database
    database: "{{ item }}"
    roles: "{{ funkwhale_db_user }}"
    grant_option: true
    privs: all
  loop:
    - "{{ funkwhale_db_user }}"
    - "{{ funkwhale_db }}"

- name: "Configure front reverse-proxy.nginx"
  template:
    src: funkwhale.conf.j2
    dest: "{{ FUNKWHALE_NGINX_SERVER_CONF }}funkwhale.conf"
  tags: molecule-notest
