---

- name: install dependeies packages for Funkwhale
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python-psycopg2
    - libldap2-dev
    - libsasl2-dev
    - build-essential
    - ffmpeg
    - libjpeg-dev
    - libmagic-dev
    - libpq-dev
    - python3-dev
    - python3-venv
    - python3-psycopg2

- name: Install pgdg package signing key (Debian/pgdg)
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8
  register: __postgresql_apt_key_result
  until: __postgresql_apt_key_result is succeeded
  retries: 5
  delay: 5

- name: Install pgdg repository (Debian/pgdg)
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    update_cache: true

- name: prepare of ENV.INFRA for Funkwhale
  package:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql-10
#??    - postgresql-contrib
    - postgresql-client-10
    - redis-server
    - nginx

### config.yml
- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/postgresql/10/main/PG_VERSION"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  loop:
    - postgresql

- name: Revoke access from local user mary on database mydb.
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/10/main/pg_hba.conf
    contype: local
    users: postgres
    databases: all
    method: peer
    state: absent

- name: Revoke access from local user mary on database mydb.
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/10/main/pg_hba.conf
    contype: host
    users: all
    databases: all
    address: "{{ item }}"
    method: md5
    state: absent
  loop:
    - "127.0.0.1/32"
    - "::1/128"

- name: Grant user funkwhale
  postgresql_pg_hba:
    dest: /etc/postgresql/10/main/pg_hba.conf
    contype: local
    users: postgres
    databases: all
    method: trust
    create: true

- name: Grant user funkwhale
  postgresql_pg_hba:
    dest: /etc/postgresql/10/main/pg_hba.conf
    contype: host
    users: all
    source: "{{ item }}"
    databases: all
    method: trust
    create: true
  loop:
    - "127.0.0.1/32"
    - "::1/128"

- name: Restart SystemD unit postgresql10
  ansible.builtin.systemd:
    state: restarted
    name: postgresql@10-main
    enabled: yes

- name: "Create app database"
  postgresql_db:
    name: "{{ item }}"
    state: present
    encoding: UTF-8
    template: template0
  loop:
    - funkwhale
    - funkwhale_database

- name: "Create db user"
  postgresql_user:
    state: present
    name: funkwhale
    password: ""
    role_attr_flags: SUPERUSER

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ item }}"
    roles: funkwhale
    grant_option: yes 
    privs: all
  loop:
    - funkwhale
    - funkwhale_database
