---
- name: install dependeies packages for Funkwhale
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-venv
    - libldap2-dev
    - libsasl2-dev
    - build-essential
    - ffmpeg
    - libjpeg-dev
    - libmagic-dev
    - libpq-dev
    - postgresql-client
    - python3-dev
    - python3-psycopg2

- name: prepare && start of ENV.INFRA for Funkwhale
  package:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql
    - postgresql-contrib
    - redis
    - nginx

# enable && start