---

- import_tasks: preflight.yml


- import_tasks: rhel.yml
  when: ansible_os_family == 'RedHat'


- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'


- name: Install wheel to virtualenv
  pip:
    name: wheel
    virtualenv: "{{ base_directory }}/{{ service_name }}/virtualenv"
    virtualenv_command: /usr/bin/python3 -m venv


- name: Upgrade pip to the last version
  pip:
    name: pip
    virtualenv: "{{ base_directory }}/{{ service_name }}/virtualenv"
    virtualenv_command: /usr/bin/python3 -m venv


#- name: Install requirements
#  pip:
#    requirements: "{{ base_directory }}/{{ service_name }}/api/requirements.txt"
#    virtualenv: "{{ base_directory }}/{{ service_name }}/virtualenv"
#    virtualenv_command: /usr/bin/python3 -m venv


- name: Configure beat systemd service
  template:
    src: funkwhale-beat.service.j2
    dest: "/etc/systemd/system/funkwhale-beat.service"
#  notify: Restart funkwhale


- name: Configure server systemd service
  template:
    src: funkwhale-server.service.j2
    dest: "/etc/systemd/system/funkwhale-server.service"
#  notify: Restart funkwhale


- name: Configure worker systemd service
  template:
    src: funkwhale-worker.service.j2
    dest: "/etc/systemd/system/funkwhale-worker.service"
#  notify: Restart funkwhale


- name: Configure systemd target
  template:
    src: funkwhale.target.j2
    dest: "/etc/systemd/system/funkwhale.target"
#  notify: Restart funkwhale


- name: Configure service
  template:
    src: env.j2
    dest: "{{ base_directory }}/{{ service_name }}/config/.env"
    owner: funkwhale
    group: funkwhale
    mode: 0600
#  notify: Restart funkwhale


- name: Run an initial migration
  django_manage:
    command: migrate
    app_path: "{{ base_directory }}/{{ service_name }}/api"
    pythonpath: "/usr/bin/python3"
    virtualenv: "{{ base_directory }}/{{ service_name }}/virtualenv"
  tags: molecule-notest


- name: Configure nginx
  template:
    src: funkwhale.conf.j2
    dest: "/etc/nginx/sites-enabled/funkwhale.conf"
  tags: molecule-notest
