---
- name: Validate configuration
  ansible.builtin.assert:
    that:
      - funkwhale_domain is defined
      - funkwhale_secret is defined
      - funkwhale_domain is defined
      - funkwhale_db is defined
      - funkwhale_db_user is defined
      - funkwhale_db_password is defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' or ansible_os_family == 'AlmaLinux'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Debian'

- name: Check out develop branch
  ansible.builtin.git:
    repo: 'https://dev.funkwhale.audio/funkwhale/funkwhale'
    dest: /srv/funkwhale
    version: develop

- name: Add the user
  ansible.builtin.user:
    name: funkwhale
    shell: /usr/bin/nologin
    home: /srv/funkwhale
    #    create_home: true

- name: Install wheel to virtualenv
  ansible.builtin.pip:
    name: wheel
    virtualenv: /srv/funkwhale/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Upgrade pip to the last version
  ansible.builtin.pip:
    name: pip
    virtualenv: /srv/funkwhale/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv


# TODO postgres and redis must be on the same host
- name: Configure beat systemd service
  ansible.builtin.template:
    src: funkwhale-beat.service.j2
    dest: "/etc/systemd/system/funkwhale-beat.service"
    mode: '0644'


- name: Configure server systemd service
  ansible.builtin.template:
    src: funkwhale-server.service.j2
    dest: "/etc/systemd/system/funkwhale-server.service"
    mode: '0644'

- name: Configure worker systemd service
  ansible.builtin.template:
    src: funkwhale-worker.service.j2
    dest: "/etc/systemd/system/funkwhale-worker.service"
    mode: '0644'

- name: Configure systemd target
  ansible.builtin.template:
    src: funkwhale.target.j2
    dest: "/etc/systemd/system/funkwhale.target"
    mode: '0644'

- name: Create config directory
  ansible.builtin.file:
    path: /srv/funkwhale/config
    owner: funkwhale
    group: root
    state: directory
    mode: '0755'

- name: Configure service
  ansible.builtin.template:
    src: env.j2
    dest: "/srv/funkwhale/config/.env"
    owner: funkwhale
    group: root
    mode: '0600'

- name: Run an initial migration
  community.general.django_manage:
    command: migrate
    app_path: "/srv/funkwhale/api"
    pythonpath: "/usr/bin/python3"
    virtualenv: "/srv/funkwhale/virtualenv"
  tags: molecule-notest

- name: Configure nginx
  ansible.builtin.template:
    src: funkwhale.conf.j2
    dest: "/etc/nginx/conf.d/funkwhale.conf"
    owner: root
    group: root
    mode: '0644'

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  tags: molecule-notest

- name: Start redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true
  tags: molecule-notest
