- name: install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
  - build-essential
  - curl
  - ffmpeg
  - git
  - libffi-dev
  - libjpeg-dev
  - libldap2-dev
  - libmagic-dev
  - libpq-dev
  - libsasl2-dev
  - libssl-dev
  - libxml2-dev
  - libxslt1-dev
  - make
  - nginx
  - postgresql-client
  - python3-dev
  - python3-venv
  - redis-server
  - unzip
  - zlib1g-dev
