dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: false  
driver:
  name: docker
lint: |
  yamllint -c molecule/default/yamllint.yml -f colored .
platforms:
  - name: ansible-role-funkwhale-debian11
    image: "geerlingguy/docker-debian11-ansible"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: ansible-role-funkwhale-test-amazon2
    image: geerlingguy/docker-amazonlinux2-ansible
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    parallelize_platforms: true    
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    options:
      exclude:
        - molecule/default/playbook.yml
      x:
        - 204  # Lines should be no longer than 160 chars
        - 403  # Package installs should not use latest
        - 502  # All tasks should be named
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  directory: ${MOLECULE_PROJECT_DIRECTORY}/molecule/tests/  
  lint:
    name: flake8
