---
# Test role ansible-role-funkwhale on OS: Debian 10, Amazon Linux 2
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
#  - name: ansible-role-funkwhale-test-amazon2
#    image: geerlingguy/docker-amazonlinux2-ansible
#    command: ${MOLECULE_COMMAND:-""}
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    privileged: true
#    pre_build_image: true
#    parallelize_platforms: true
  - name: ansible-role-funkwhale-test-debian10
    image: geerlingguy/docker-debian10-ansible
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    parallelize_platforms: true
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
  config_options:
    defaults:
      fact_caching: jsonfile
  lint:
    name: ansible-lint
    options:
      exclude:
        - molecule/default/playbook.yml
      x:
        - 204  # Lines should be no longer than 160 chars
        - 403  # Package installs should not use latest
        - 502  # All tasks should be named
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
