extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments-indentation: enable
  document-start: enable
  line-length: enable
  truthy: enable
