---
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments-indentation: disable
  document-start: enable
  line-length: disable
  truthy: enable
